### ISSUE TITLE
TypeError: a[c] is not a function Next js/React JS

### ISSUE THREAD

**Issue by vaulstein** [microsoft/clarity#247]
I am trying to add clarity to a Next JS project. I have followed some online resources which have shown that scripts for Google tag manager/Clarity can be added in the below way.

File: app.tsx

```
<Script
        id="clarity"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
          (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
        })(window, document, "clarity", "script", '${CLARITY_KEY}');`,
        }}
      />
```

This code triggers successfully and is fetching another script file and trying to inject it, which throws error while execution. Below is the script which is called by Clarity and throws an error:

```
!function(c, l, a, r, i, t, y) {
    if (a[c].v || a[c].t)
        return a[c]("event", c, "dup." + i.projectId);
    a[c].t = !0,
    (t = l.createElement(r)).async = !0,
    t.src = "https://www.clarity.ms/eus2-f/s/0.6.34/clarity.js",
    (y = l.getElementsByTagName(r)[0]).parentNode.insertBefore(t, y),
    a[c]("start", i),
    a[c].q.unshift(a[c].q.pop())
}("clarity", document, window, "script", {
    "projectId": "XmaskedX",
    "upload": "https://www.clarity.ms/eus2-f/collect",
    "expire": 365,
    "cookies": ["_uetmsclkid", "_uetvid"],
    "track": true,
    "lean": false,
    "content": true,
    "extract": [0, 501, "window.navigator.hardwareConcurrency", 0, 502, "window.navigator.deviceMemory", 0, 503, "window.navigator.platform", 0, 504, "window.navigator.maxTouchPoints", 0, 505, "window.devicePixelRatio", 0, 510, "screen.isExtended", 0, 511, "navigator.cookieEnabled", 0, 512, "navigator.onLine", 0, 513, "navigator.doNotTrack", 0, 514, "navigator.connection", 0, 515, "navigator.vendor", 0, 516, "navigator.product", 0, 517, "navigator.productSub", 0, 518, "navigator.pdfViewerEnabled"],
    "fraud": [[1, "input[type=\u0027email\u0027]"]],
    "report": "https://www.clarity.ms/report/eus2f"
});
```
[Successful 1st call](https://ibb.co/vjyyDrb)
Error thrown is as below:

> line 8 Uncaught TypeError: a[c] is not a function a[c]("start", i) // throws error on this line

Have debugged a is window and c is a string "clarity".

The code works fine in a React project but is not working in Next JS.

**Comment by AsazuTaiga** [comment]
I ran into the same problem and came across https://stackoverflow.com/questions/72210974/microsoft-clarity-not-working-with-next-js-react-js-project.
The cause is very simple, but a trap.
`id="claryty"` breaks the library. Try to change it into `id="ms_clarity"` or whatever.

**Comment by LhonRafaat** [comment]
Im receiving same error message in production, but I am not using Clarity in my project, I use Google Analytics instead
`TypeError: a[C] is not a function
    at e (/----/.next/server/chunks/538.js:9:148504)
    at O (/----/.next/server/chunks/538.js:9:18624)
    at eh (/----/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/----/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671)
    at ek (/----/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138145)
    at Array.toJSON (/----/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
    at stringify (<anonymous>)
    at eR (/----/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219)
    at eE (/----/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
    at Timeout._onTimeout (/----/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475) {
  digest: '1147893119'
`

Nextjs -v : 14.2.3
Nodejs -v : 20.10.0


could the GA possibly be causing the issue?
but looks like the error is coming from Nextjs
