### ISSUE TITLE
Getting crash in react native 

### ISSUE THREAD

**Issue by AmanKumarSingh01** [microsoft/clarity#401]
at org.glassfish.json.JsonProviderImpl.createDiff(JsonProviderImpl.java:2)
       at javax.json.Json.createDiff(Json.java:4)
       at com.microsoft.clarity.models.ingest.mutation.MutationEvent$Companion.getMutationPayload(:17)
       at com.microsoft.clarity.models.ingest.mutation.MutationEvent$Companion.make(:5)

**Comment by fansilva1991** [comment]
Same issue here!

The crash is happening on Android, while the app is running.

Here is my information:

### React Native Info

```
System:
    OS: macOS 13.4
    CPU: (8) x64 Apple M1 Pro
    Memory: 20.79 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/projects/sportninja/client/mobile/node_modules/.bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### MS Clarity Library version

```
 "react-native-clarity": "^0.0.4",
```

### Error Log

```
FATAL EXCEPTION: Thread-13
PID: 30685
java.lang.OutOfMemoryError: Failed to allocate a 35544 byte allocation with 8856 free bytes and 8856B until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.reflect.Array.createMultiArray(Native Method)
	at java.lang.reflect.Array.newInstance(Array.java:125)
	at org.glassfish.json.JsonPatchImpl$DiffGenerator.diffArray(JsonPatchImpl.java:276)
	at org.glassfish.json.JsonPatchImpl$DiffGenerator.diff(JsonPatchImpl.java:242)
	at org.glassfish.json.JsonPatchImpl$DiffGenerator.lambda$diffObject$0$org-glassfish-json-JsonPatchImpl$DiffGenerator(JsonPatchImpl.java:251)
	at org.glassfish.json.JsonPatchImpl$DiffGenerator$$ExternalSyntheticLambda0.accept(Unknown Source:10)
	at java.util.Map.forEach(Map.java:659)
	at org.glassfish.json.JsonPatchImpl$DiffGenerator.diffObject(JsonPatchImpl.java:249)
	at org.glassfish.json.JsonPatchImpl$DiffGenerator.diff(JsonPatchImpl.java:240)
	at org.glassfish.json.JsonPatchImpl$DiffGenerator.diff(JsonPatchImpl.java:229)
	at org.glassfish.json.JsonPatchImpl.diff(JsonPatchImpl.java:154)
	at org.glassfish.json.JsonProviderImpl.createDiff(JsonProviderImpl.java:238)
	at javax.json.Json.createDiff(Json.java:399)
	at com.microsoft.clarity.models.ingest.mutation.MutationEvent$Companion.getMutationPayload(Unknown Source:17)
	at com.microsoft.clarity.models.ingest.mutation.MutationEvent$Companion.make(Unknown Source:5)
	at a.a.a.s.f.a(Unknown Source:38)
	at a.a.a.s.b$a.a(Unknown Source:5)
	at a.a.a.s.a$f.invoke(Unknown Source:15)
	at a.a.a.y.b$a.a(Unknown Source:5)
	at a.a.a.y.b$a.a(Unknown Source:11)
	at a.a.a.s.a.a(Unknown Source:36)
	at a.a.a.s.a$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by ibradwan** [comment]
We have released a new version that fixes this issue. Please consider upgrading to the latest version.

**Comment by ibradwan** [comment]
Please update to the latest version '1.3.2' and you should not see this issue anymore.

**Comment by arjunsinghsaini** [comment]
@ibradwan  Getting this same issue with the latest clarity library '2.5.2' on Android Samsung s22 ultra device - 

Failed to allocate a 186407808 byte allocation with 25165824 free bytes and 61MB until OOM, target footprint 229073168, growth limit 268435456
java.util.Arrays.copyOf (Arrays.java:3585)
java.lang.AbstractStringBuilder.ensureCapacityInternal (AbstractStringBuilder.java:177)
java.lang.AbstractStringBuilder.append (AbstractStringBuilder.java:753)
java.lang.StringBuilder.append (StringBuilder.java:257)

**Comment by ibradwan** [comment]
Hi,
At what rate are you getting this error?

**Comment by arjunsinghsaini** [comment]
@ibradwan As i can check this crash frequency is around 2 crashes in 1000 session. Is it due to less memory space availability in phone? Can we do some thing or suggest any thing to user for handling this crash?

**Comment by ibradwan** [comment]
This could happen because the devices were low on memory any way, and it just happened that Clarity was the piece of code trying to allocate memory at that critical time. However, collecting more data points might help here, like:
1) The overall memory consumption of the device at the time of the incident.
2) The average memory consumption of your app alone on the same device model.
3) Your app memory consumption at the time of the incident.

By looking at these data points, you should be able to deduce whether Clarity had anything to do with this or not.

Also, another question: are you using heavy images/fonts in your application?
