### ISSUE TITLE
ReactNative: Exception in native call java.lang.RuntimeException: Could not invoke Clarity.initialize

### ISSUE THREAD

**Issue by venukaaventude** [microsoft/clarity#524]
**i try to use clarity on my react native project. dependency integrate successfully but when run the app getting this error message.**

```
E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Could not invoke Clarity.initialize
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) 
        at java.lang.Thread.run(Thread.java:1012) 
     Caused by: java.lang.NoSuchMethodError: No static method isInitialized()Z in class Landroidx/work/WorkManager; or its super classes (declaration of 'androidx.work.WorkManager' appears in /data/app/~~Fr4mzmpLIRP1mrLSV-BIaw==/se.transvoice.tolka-nUkxioNGcNIULvGZW8keGg==/base.apk)
        at com.microsoft.clarity.b.invoke(SourceFile:1)
        at com.microsoft.clarity.n.m.a(Unknown Source:22)
        at com.microsoft.clarity.c.invoke(SourceFile:3)
        at com.microsoft.clarity.n.e.a(Unknown Source:5)
        at com.microsoft.clarity.n.d.invoke(SourceFile:1)
        at com.microsoft.clarity.n.m.a(Unknown Source:22)
        at com.microsoft.clarity.n.e.a(SourceFile:3)
        at com.microsoft.clarity.a$a.a(Unknown Source:20)
        at com.microsoft.clarity.Clarity.initialize(Unknown Source:11)
        at com.microsoft.clarity.reactnative.ClarityModule.initialize(ClarityModule.kt:36)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) 
        at java.lang.Thread.run(Thread.java:1012) 
```
**this is project dependencies**
"react": "17.0.2",
"react-native": "0.68.0",
"react-native-clarity": "^2.0.1",

        kotlinVersion = "1.6.0"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "17.+" // or set latest version
        firebaseVersion = "17.3.4"
        androidMapsUtilsVersion = "0.5+"

![clarity 1](https://github.com/microsoft/clarity/assets/116064318/579a0e9f-5ba5-4f31-8348-d398cbd5987c)
![clarity 2](https://github.com/microsoft/clarity/assets/116064318/aa2d4e10-7c91-4b8a-8cbb-a35d89bce2db)

**Comment by Jaybee4real** [comment]
@venukaaventude How did you solve this?

**Comment by venukaaventude** [comment]
> @venukaaventude How did you solve this?

yes, i have fixed that issue

**Comment by Jaybee4real** [comment]
How

**Comment by venukaaventude** [comment]
> How
what is your project RN version?

**Comment by Jaybee4real** [comment]
0.71.6

**Comment by venukaaventude** [comment]
> 0.71.6
in your project android **build.gradle** file what is the **androidx.work:work-runtime** version you have

**Comment by Jaybee4real** [comment]
<img width="631" alt="Screenshot 2024-03-20 at 8 12 18 AM" src="https://github.com/microsoft/clarity/assets/51276685/eb6c4013-6816-4814-99fd-9f1e557def4b">

This is what it looks like, don't think I have that

**Comment by venukaaventude** [comment]
> <img alt="Screenshot 2024-03-20 at 8 12 18 AM" width="631" src="https://private-user-images.githubusercontent.com/51276685/314405796-eb6c4013-6816-4814-99fd-9f1e557def4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTkzMDYsIm5iZiI6MTcxMDkxOTAwNiwicGF0aCI6Ii81MTI3NjY4NS8zMTQ0MDU3OTYtZWI2YzQwMTMtNjgxNi00ODE0LTk5ZmQtOWYxZTU1N2RlZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlODZiNTViOGU0YTNkNTE3YjM4NGI0ZjRlZTFkMjg5ZmM4YmM5MzRiMjFmNzQ2ZTAwYWVkYjNlYzViMzQyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5joKh33CzHoW4EH2UkcEhVi_YoxP8oX_VIsxP_E2esk">
> This is what it looks like, don't think I have that

can you check dependencies tree in project and copy it here

**Comment by Jaybee4real** [comment]
NVM i just upgraded to the latest version released 20 hours ago, and it fixed it

**Comment by pankaj-dharmik** [comment]
How did you solved this?

**Comment by venukaaventude** [comment]
> How did you solved this?

what is your project RN version?
