### ISSUE TITLE
Jetpack Compose Support

### ISSUE THREAD

**Issue by BcanGRG** [microsoft/clarity#628]
Hello clarity team,

We want to use Clarity in our Android application, but our application has pages written with Jetpack Compose and cannot work with Clarity in harmony with these pages.

When will Jetpack compose support come?

**Comment by aligkts** [comment]
++

**Comment by ibradwan** [comment]
We've just released our first compose package (clarity-compose) :) Please give it a shot and let us know your feedback.

**Comment by ibradwan** [comment]
All what you have to do is to switch to the "clarity-compose" package and you should start seeing compose views in playback. The docs will be updates soon to include more details.

**Comment by nikhilbiju67** [comment]
I couldn't find the "clarity-compose" can you help?

**Comment by SaadeldinBadr** [comment]
Hello @nikhilbiju67, which version of Jetpack Compose are you using?

**Comment by nikhilbiju67** [comment]
I am using implementation(platform("androidx.compose:compose-bom:2024.06.00"))
@SaadeldinBadr

**Comment by SaadeldinBadr** [comment]
@nikhilbiju67 Could you please set log level in Clarity config to `LogLevel.Verbose` and share the logs with `tag:Clarity` here for a brief session? Also provide me with your app's package name if possible.

**Comment by Wysel** [comment]
Hello there, 
I just started playing with Microsoft Clarity. I have integrated Clarity into my project, which is mostly Jetpack Compose with few legacy view based screens. Clarity version: com.microsoft.clarity:clarity-compose:2.5.1
Non-composable activities appears to be captured correctly, but all composable screens are blank. Here's a exception that I get:

[SourceFile::a] Exception in captureAndroidComposeView: java.lang.NullPointerException
2024-09-30 10:38:53.102  1185-1185  Clarity                 gov.nyc.doitt.ThreeOneOne            E  [SourceFile::a] null
2024-09-30 10:38:53.102  1185-1185  Clarity                 gov.nyc.doitt.ThreeOneOne            E  [SourceFile::a] java.lang.NullPointerException (Ask Gemini)
                                                                                                    	at com.microsoft.clarity.e.b.a(Unknown Source:32)
                                                                                                    	at com.microsoft.clarity.e.b.a(SourceFile:6)
                                                                                                    	at com.microsoft.clarity.e.d.a(SourceFile:84)
                                                                                                    	at com.microsoft.clarity.e.d.a(SourceFile:84)
                                                                                                    	at com.microsoft.clarity.e.d.a(SourceFile:84)
                                                                                                    	at com.microsoft.clarity.e.d.a(SourceFile:84)
                                                                                                    	at com.microsoft.clarity.e.d.a(SourceFile:84)
                                                                                                    	at com.microsoft.clarity.e.d$d.invoke(SourceFile:3)
                                                                                                    	at com.microsoft.clarity.e.d.a(SourceFile:20)
                                                                                                    	at com.microsoft.clarity.f.j.invoke(SourceFile:3)
                                                                                                    	at com.microsoft.clarity.n.k.a(Unknown Source:22)
                                                                                                    	at com.microsoft.clarity.f.k$a.invoke(SourceFile:12)
                                                                                                    	at com.microsoft.clarity.n.d.a(Unknown Source:5)
                                                                                                    	at com.microsoft.clarity.n.c.invoke(SourceFile:1)
                                                                                                    	at com.microsoft.clarity.n.k.a(Unknown Source:22)
                                                                                                    	at com.microsoft.clarity.n.d.a(SourceFile:5)
                                                                                                    	at com.microsoft.clarity.f.k.run(SourceFile:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9063)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    	
Thank you for your help.

**Comment by SaadeldinBadr** [comment]
Hello @Wysel ,
which version of Jetpack Compose are you using?

**Comment by Wysel** [comment]
1.7.2

**Comment by Wysel** [comment]
Thanks @SaadeldinBadr, I was afraid that that's what's happening :)  When do you expect to provide support for 1.7.2?

**Comment by yousef96m** [comment]
Hello clarity team,

I use `clarity-compose = { module = "com.microsoft.clarity:clarity-compose", version.ref = "version-clarity-compose" }`
`version-clarity-compose = "3.0.2"`

The recording in the dashboard has a white screen. Do you know how I can fix this issue?

**Comment by yousef96m** [comment]
@ibradwan Thanks for the update, waiting for you ان شاء الله

**Comment by SaadeldinBadr** [comment]
Hello Everyone,
We've just released `clarity-compose:3.1.0` which supports jetpack compose `1.7.*`, Feel free to give it a try!
