### ISSUE TITLE
com.microsoft.clarity.g.a$a.run java.net.SocketException - Software caused connection abort

### ISSUE THREAD

**Issue by dawon-swing** [microsoft/clarity#724]
If this is an issue you're seeing in https://clarity.microsoft.com please reach out to clarityms@microsoft.com with the details of your bug along with your project ID or a link to your project page.

---

For all other issues continue below:

Please also add all relevant labels from the list of existing ones. 

**Describe the bug**

com.microsoft.clarity.g.a$a.run
java.net.SocketException - Software caused connection abort

**I recently integrated Clarity into my Android app, and an issue has been reported in Firebase Crashlytics. Unfortunately, there are no screenshots available, but I'll provide the stack trace first.**

![Image](https://github.com/user-attachments/assets/10abcdf1-06af-47ff-a579-75ee8df142bf)
[stacktrace.txt](https://github.com/user-attachments/files/18205049/stacktrace.txt)

**Repro Steps**
If applicable, steps to reproduce the behavior.

**Screenshots**

**Project info**
If this is an issue happening in a specific project,
- Type: website/iOS/Android project
- Website info: For website projects, include a link

**Browser info:**
 - OS: Windows/iOS/Android...
 - Browser: Edge/Chrome/Safari...

**Comment by ibradwan** [comment]
Thanks for reporting this issue. We’ve released a new version (3.0.2 for native Android & 4.0.5 for React Native) that should address this issue. Please give it a shot.

**Comment by felipeemoreno** [comment]
> Thanks for reporting this issue. We’ve released a new version (3.0.2 for native Android & 4.0.5 for React Native) that should address this issue. Please give it a shot.

i had the same error **Software caused connection abort** whith the last version 4.0.5 for React Native.

`java.net.SocketException: Software caused connection abort
    at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
    at java.net.SocketInputStream.read(SocketInputStream.java:173)
    at java.net.SocketInputStream.read(SocketInputStream.java:143)
    at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
    at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
    at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
    at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
    at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
    at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
    at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
    at com.microsoft.clarity.C6.a.run
    at java.util.TimerThread.mainLoop(Timer.java:573)
    at java.util.TimerThread.run(Timer.java:523)`

**Comment by ibradwan** [comment]
Hi @felipeemoreno,

Thanks for sharing your feedback. A couple of questions to help us debug it:
1. Is it consistent? If no, is there a pattern for it?
2. Could you please share your project id and Android package name on clarity-apps-support@microsoft.com
3. Does this error cause the app to crash?

Thanks for your cooperation!

**Comment by bolt-vikas** [comment]
Hi @ibradwan,

we’ve started observing a significant number of crashes logged in Firebase Crashlytics. 
library version -  3.1.0

Crash log -
     Fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
       at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
       at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
       at com.google.firebase.perf.network.InstrURLConnectionBase.getResponseCode(InstrURLConnectionBase.java:197)
       at com.google.firebase.perf.network.InstrHttpURLConnection.getResponseCode(InstrHttpURLConnection.java:92)
       at com.microsoft.clarity.g.a.run(SourceFile:206)
       at java.util.TimerThread.mainLoop(Timer.java:573)
       at java.util.TimerThread.run(Timer.java:523)


will upgrading to 3.1.1 solve this exception?
We have already mailed the details to clarity-apps-support@microsoft.com.

**Comment by dawon-swing** [comment]
Reproduced in 3.1.0

**Comment by ibradwan** [comment]
We've just released Android version 3.1.2 and React Native version 4.1.2 which include a fix for this issue. Thanks for your proactivity in reporting the issues.

**Comment by felipeemoreno** [comment]
Hi, sorry for the late response.

Today i updated the package for v4.1.3 but still got the crash, i sent the email for you.

> Hi [@felipeemoreno](https://github.com/felipeemoreno),
> 
> Thanks for sharing your feedback. A couple of questions to help us debug it:
> 
> 1. Is it consistent? If no, is there a pattern for it?
> 2. Could you please share your project id and Android package name on [clarity-apps-support@microsoft.com](mailto:clarity-apps-support@microsoft.com)
> 
> Thanks for your cooperation!

**Comment by pelikanexa** [comment]
> [@ibradwan](https://github.com/ibradwan) Reproduced in 3.1.0

+ 1

**Comment by ibradwan** [comment]
@pelikanexa please upgarde to the latest version. We addressed this issue a couple of weeks ago in version 3.1.2.

**Comment by pelikanexa** [comment]
> [@pelikanexa](https://github.com/pelikanexa) please upgarde to the latest version. We addressed this issue a couple of weeks ago in version 3.1.2.

Tks, I see version 3.1.3 under Maven Central.  May I use that instead of 3.1.2?

**Comment by ibradwan** [comment]
Yes please update to the latest one.
